import logging
import numpy as np
import os

try:
    from xgboost import XGBClassifier
    _XGB_AVAILABLE = True
except ImportError:
    _XGB_AVAILABLE = False

logger = logging.getLogger(__name__)

class MetaLabeler:
    """
    XGBoost Meta-Labeler.
    Acts as a secondary filter. Given a trade signal generated by a heuristic strategy (like ORB),
    the meta-labeler predicts the probability of that specific trade hitting its target.
    If the probability is below a threshold (e.g., 60%), it vetoes the trade.
    """
    def __init__(self, model_path="models/meta_labeler.pkl"):
        self.model_path = model_path
        self.model = None
        self.is_loaded = False
        
        if _XGB_AVAILABLE and model_path:
            self._load_model()
            
    def _load_model(self):
        try:
            import joblib
            if os.path.exists(self.model_path):
                self.model = joblib.load(self.model_path)
                self.is_loaded = True
        except Exception as e:
            logger.warning(f"MetaLabeler failed to load model at {self.model_path}: {e}")
            
    def evaluate_trade(self, trade_signal, market_context=None, required_prob=0.60):
        """
        Evaluate a trade signal using the XGBoost meta-labeling model.
        Returns (bool, float): (approved, probability_of_success)
        """
        if not self.is_loaded or self.model is None:
            # Safe degradation: If model isn't available, approve the trade (Fail Open)
            return True, 1.0
            
        market_context = market_context or {}
        try:
            features = self._extract_features(trade_signal, market_context)
            if features is None:
                return True, 1.0 # Safe degradation
                
            X = np.array([features])
            
            # Predict probabilities. Assuming class 1 is "Success/Hit Target"
            probs = self.model.predict_proba(X)[0]
            
            if len(probs) > 1:
                prob_success = float(probs[1])
            else:
                # If model was accidentally trained with only 1 class
                prob_success = float(probs[0])
                
            approved = prob_success >= required_prob
            return approved, prob_success
            
        except Exception as e:
            logger.error(f"MetaLabeler evaluation failed: {e}")
            return True, 1.0 # Safe fallback
            
    def _extract_features(self, trade_signal, market_context):
        """
        Extracts the fixed-length feature vector required by the XGBoost model.
        """
        try:
            return [
                float(trade_signal.get("confidence", 50)),
                float(market_context.get("vix", 15.0)),
                float(market_context.get("dealer_gamma_exposure", 0.0)),
                float(market_context.get("cumulative_volume_delta", 0.0)),
                float(trade_signal.get("lot_size", 1.0))
            ]
        except Exception:
            return None
