from enum import Enum


class DeliveryRole(str, Enum):
    PRODUCT_OWNER = "PRODUCT_OWNER"
    BUSINESS_ANALYST = "BUSINESS_ANALYST"
    SOLUTION_ARCHITECT = "SOLUTION_ARCHITECT"
    SYSTEM_ARCHITECT = "SYSTEM_ARCHITECT"
    QUANT_RESEARCH_ARCHITECT = "QUANT_RESEARCH_ARCHITECT"
    BACKEND_DEVELOPER = "BACKEND_DEVELOPER"
    DATA_QUANT_DEVELOPER = "DATA_QUANT_DEVELOPER"
    INTEGRATION_DEVELOPER = "INTEGRATION_DEVELOPER"
    UI_DEVELOPER = "UI_DEVELOPER"
    QA_ENGINEER = "QA_ENGINEER"
    SENIOR_QA = "SENIOR_QA"
    UAT_REVIEWER = "UAT_REVIEWER"
    RELEASE_MANAGER = "RELEASE_MANAGER"
    PRODUCTION_SRE = "PRODUCTION_SRE"


class AgentMapping(str, Enum):
    HERMES = "HERMES"
    GSD = "GSD"
    GRILL_ME = "GRILL_ME"


AGENT_ROLE_MAP = {
    AgentMapping.HERMES: frozenset({DeliveryRole.SOLUTION_ARCHITECT, DeliveryRole.SYSTEM_ARCHITECT,
                                    DeliveryRole.QUANT_RESEARCH_ARCHITECT}),
    AgentMapping.GSD: frozenset({DeliveryRole.BACKEND_DEVELOPER, DeliveryRole.DATA_QUANT_DEVELOPER,
                                 DeliveryRole.INTEGRATION_DEVELOPER, DeliveryRole.UI_DEVELOPER}),
    AgentMapping.GRILL_ME: frozenset({DeliveryRole.QA_ENGINEER, DeliveryRole.SENIOR_QA}),
}
