from enum import Enum


class DeliveryState(str, Enum):
    BACKLOG = "BACKLOG"
    REQUIREMENT_READY = "REQUIREMENT_READY"
    DESIGN_READY = "DESIGN_READY"
    IN_DEVELOPMENT = "IN_DEVELOPMENT"
    DEV_VERIFIED = "DEV_VERIFIED"
    QA_IN_PROGRESS = "QA_IN_PROGRESS"
    QA_FAILED = "QA_FAILED"
    QA_PASSED = "QA_PASSED"
    SENIOR_QA = "SENIOR_QA"
    UAT = "UAT"
    UAT_FAILED = "UAT_FAILED"
    PRODUCT_ACCEPTED = "PRODUCT_ACCEPTED"
    RELEASE_READY = "RELEASE_READY"
    RELEASE_BLOCKED = "RELEASE_BLOCKED"
    PR_OPEN = "PR_OPEN"
    CI_GREEN = "CI_GREEN"
    CI_FAILED = "CI_FAILED"
    MERGE_APPROVED = "MERGE_APPROVED"
    MERGED = "MERGED"
    PRODUCTION_VERIFIED = "PRODUCTION_VERIFIED"
    DONE = "DONE"
    BLOCKED_REQUIREMENT = "BLOCKED_REQUIREMENT"
    BLOCKED_DATA = "BLOCKED_DATA"
    BLOCKED_RESEARCH = "BLOCKED_RESEARCH"
    FAILED_VERIFICATION = "FAILED_VERIFICATION"


INITIAL_STATE = DeliveryState.BACKLOG
