from __future__ import annotations

from pathlib import Path

from .artifact_parser import parse_vwap_artifacts
from .determinism import build_determinism_fingerprint
from .ledger_oracle import certify_ledger
from .reconciliation import reconcile
from .source_discovery import discover_vwap_sources
from .source_search_manifest import SOURCE_RESOLVED, build_source_search_manifest


def build_signal_ledgers(repo_root: Path):
    """Build no signal rows until a real source manifest resolves VWAP inputs.

    This function is intentionally read-only. Full source evidence is generated by
    the explicit local evidence command and must be reviewed before execution is
    enabled.
    """

    repo_root = repo_root.resolve()
    sources = discover_vwap_sources(repo_root)
    artifacts = parse_vwap_artifacts(repo_root)
    source_manifest = build_source_search_manifest(repo_root)
    records: list[dict[str, object]] = []

    source_status = str(source_manifest["conclusion"])
    execution_status = "VWAP_EXECUTION_NOT_RUN_NO_ACCEPTED_SOURCE"
    if source_status == SOURCE_RESOLVED:
        execution_status = "VWAP_EXECUTION_PENDING_REVIEWED_SOURCE"

    execution = {
        "status": execution_status,
        "source_status": source_status,
        "reason_codes": list(source_manifest.get("reason_codes", [])),
        "execution_allowed": False,
        "broker_api_called": False,
        "is_order_action": False,
        "allowed_for_live_execution": False,
        "read_only": True,
    }
    oracle = certify_ledger(records, source_manifest=source_manifest)
    reconciliation = reconcile(records, artifacts, source_manifest)
    detail = {
        "sources": sources,
        "artifacts": artifacts,
        "execution": execution,
        "contract": {
            "status": "NOT_CREATED_NO_ACCEPTED_SOURCE",
            "strategy_id": "VWAP_RECLAIM",
        },
        "split": {
            "status": "NOT_CREATED_NO_ACCEPTED_DATASET",
        },
        "source_manifest": source_manifest,
        "oracle": oracle,
        "reconciliation": reconciliation,
        "determinism": build_determinism_fingerprint(source_manifest),
    }
    summary = {
        "oracle_verdict": oracle["verdict"],
        "execution_status": execution_status,
        "source_status": source_status,
    }
    return records, summary, detail
