import pyarrow as pa

# PyArrow Schema for Raw WebSocket frames index
RAW_INDEX_SCHEMA = pa.schema([
    ('provider', pa.string()),
    ('feed_version', pa.string()),
    ('connection_id', pa.string()),
    ('frame_sequence', pa.int64()),
    ('receive_monotonic_ns', pa.int64()),
    ('receive_wall_ts_utc', pa.string()),
    ('raw_byte_length', pa.int64()),
    ('checksum_sha256', pa.string()),
    ('message_class', pa.string()),
    ('decode_status', pa.string()),
    ('output_chunk_id', pa.string())
])

# PyArrow Schema for Provider-Neutral Normalized Ticks
NORMALIZED_TICK_SCHEMA = pa.schema([
    ('schema_version', pa.string()),
    ('capture_run_id', pa.string()),
    ('provider', pa.string()),
    ('feed_version', pa.string()),
    ('connection_id', pa.string()),
    ('subscription_lane', pa.string()),
    ('subscription_mode', pa.string()),
    ('instrument_key', pa.string()),
    ('exchange', pa.string()),
    ('segment', pa.string()),
    ('tradingsymbol', pa.string()),
    ('exchange_token', pa.string()),
    ('instrument_type', pa.string()),
    ('underlying_symbol', pa.string()),
    ('expiry', pa.string()),
    ('strike', pa.float64()),
    ('option_type', pa.string()),
    ('lot_size', pa.int64()),
    ('tick_size', pa.float64()),
    ('event_type', pa.string()),
    ('packet_type', pa.string()),
    ('source_exchange_ts', pa.int64()),
    ('provider_current_ts', pa.int64()),
    ('provider_last_trade_ts', pa.int64()),
    ('receive_wall_ts_utc', pa.string()),
    ('receive_monotonic_ns', pa.int64()),
    ('local_sequence', pa.int64()),
    ('reconnect_generation', pa.int64()),
    ('ltp', pa.float64()),
    ('last_traded_quantity', pa.int64()),
    ('close_price', pa.float64()),
    ('open', pa.float64()),
    ('high', pa.float64()),
    ('low', pa.float64()),
    ('volume', pa.int64()),
    ('average_traded_price', pa.float64()),
    ('open_interest', pa.int64()),
    ('previous_open_interest', pa.int64()),
    ('implied_volatility', pa.float64()),
    ('total_buy_quantity', pa.int64()),
    ('total_sell_quantity', pa.int64()),
    ('delta', pa.float64()),
    ('gamma', pa.float64()),
    ('theta', pa.float64()),
    ('vega', pa.float64()),
    ('rho', pa.float64()),
    ('bid_price_1', pa.float64()),
    ('bid_price_2', pa.float64()),
    ('bid_price_3', pa.float64()),
    ('bid_price_4', pa.float64()),
    ('bid_price_5', pa.float64()),
    ('bid_quantity_1', pa.int64()),
    ('bid_quantity_2', pa.int64()),
    ('bid_quantity_3', pa.int64()),
    ('bid_quantity_4', pa.int64()),
    ('bid_quantity_5', pa.int64()),
    ('ask_price_1', pa.float64()),
    ('ask_price_2', pa.float64()),
    ('ask_price_3', pa.float64()),
    ('ask_price_4', pa.float64()),
    ('ask_price_5', pa.float64()),
    ('ask_quantity_1', pa.int64()),
    ('ask_quantity_2', pa.int64()),
    ('ask_quantity_3', pa.int64()),
    ('ask_quantity_4', pa.int64()),
    ('ask_quantity_5', pa.int64()),
    ('market_status', pa.string()),
    ('decode_status', pa.string()),
    ('validation_status', pa.string()),
    ('rejection_reason', pa.string()),
    ('raw_chunk_id', pa.string()),
    ('raw_frame_offset', pa.int64()),
    ('raw_frame_sha256', pa.string())
])
