from enum import Enum


class RuleComparisonStatus(str, Enum):
    MATCH = "MATCH"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    MISSING_IN_IMPLEMENTATION = "MISSING_IN_IMPLEMENTATION"
    EXTRA_IN_IMPLEMENTATION = "EXTRA_IN_IMPLEMENTATION"
    CONFLICT = "CONFLICT"
    UNABLE_TO_VERIFY = "UNABLE_TO_VERIFY"
    REGISTRY_INCOMPLETE = "REGISTRY_INCOMPLETE"


class ParameterClassification(str, Enum):
    DECLARED_CONFIG = "DECLARED_CONFIG"
    PUBLISHED_RULE = "PUBLISHED_RULE"
    MEASURED_VALUE = "MEASURED_VALUE"
    HEURISTIC = "HEURISTIC"
    MAGIC_NUMBER = "MAGIC_NUMBER"
    UNKNOWN = "UNKNOWN"


class HeuristicClassification(str, Enum):
    SAFE_COMMENT = "SAFE_COMMENT"
    CONFIGURATION = "CONFIGURATION"
    HEURISTIC_RISK = "HEURISTIC_RISK"
    EXECUTION_RISK = "EXECUTION_RISK"
    PROBABILITY_LABEL_RISK = "PROBABILITY_LABEL_RISK"
    UNKNOWN = "UNKNOWN"


class IndicatorStatus(str, Enum):
    DECLARED_AND_USED = "DECLARED_AND_USED"
    DECLARED_BUT_NOT_FOUND = "DECLARED_BUT_NOT_FOUND"
    USED_BUT_NOT_DECLARED = "USED_BUT_NOT_DECLARED"
    UNUSED = "UNUSED"
    UNKNOWN = "UNKNOWN"


class ImplementationVerdict(str, Enum):
    IMPLEMENTATION_VERIFIED = "IMPLEMENTATION_VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    IMPLEMENTATION_MISMATCH = "IMPLEMENTATION_MISMATCH"
    REGISTRY_INCOMPLETE = "REGISTRY_INCOMPLETE"
    UNABLE_TO_VERIFY = "UNABLE_TO_VERIFY"
    REQUIRES_MANUAL_REVIEW = "REQUIRES_MANUAL_REVIEW"
    HARDENED_ENGINE_VERIFIED = "HARDENED_ENGINE_VERIFIED"
    HARDENED_ENGINE_MISMATCH = "HARDENED_ENGINE_MISMATCH"
    HARDENED_ENGINE_NOT_FOUND = "HARDENED_ENGINE_NOT_FOUND"
