#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np


def _is_selected(candidate: dict[str, Any]) -> bool:
    if "selected" in candidate:
        return bool(candidate.get("selected"))
    return str(candidate.get("status") or "").upper() == "PASSED"


def _candidate_timestamp(candidate: dict[str, Any]) -> str | None:
    for field in (
        "entry_eval_time",
        "signal_time",
        "timestamp",
        "source_timestamp",
    ):
        value = candidate.get(field)
        if value:
            return str(value)
    return None


def _candidate_score(candidate: dict[str, Any]) -> float | None:
    # Only use fields whose contract is an actual selection/ranking score.
    # Cost-hurdle margin has different units and must not be mixed into this audit.
    for field in ("selection_score", "score", "rank_score"):
        value = candidate.get(field)
        if value is not None:
            try:
                return float(value)
            except (TypeError, ValueError):
                return None
    return None


def _capacity_metadata(
    metadata: dict[str, Any],
    ledger_summary: dict[str, Any],
) -> dict[str, Any]:
    """Prefer capacity values generated by the same ledger run.

    `simulation_metadata.json` can describe a prior/full-universe run and is not
    authoritative for a date-sliced parameter-discovery pass. The ledger summary
    is emitted atomically by the generator and therefore owns the denominator.
    """
    resolved = dict(metadata)
    cap = ledger_summary.get("cap_saturation", {})
    if cap:
        resolved["active_symbol_days"] = cap.get(
            "active_symbol_days", resolved.get("active_symbol_days", 0)
        )
        resolved["max_trades_per_symbol_day"] = cap.get(
            "max_trades_per_symbol_day",
            resolved.get("max_trades_per_symbol_day", 0),
        )
    return resolved


def audit_selection_quality(
    candidates: list[dict[str, Any]],
    metadata: dict[str, Any],
) -> dict[str, Any]:
    failed_blockers: set[str] = set()
    active_symbol_days = int(metadata.get("active_symbol_days", 0) or 0)
    max_trades_per_symbol_day = int(
        metadata.get("max_trades_per_symbol_day", 0) or 0
    )
    if active_symbol_days <= 0 or max_trades_per_symbol_day <= 0:
        failed_blockers.add("SELECTION_CAPACITY_METADATA_MISSING")

    selected_scores: list[float] = []
    rejected_scores: list[float] = []
    selected_without_score = 0
    rejected_without_score = 0
    symbol_day_counts: defaultdict[str, int] = defaultdict(int)

    for candidate in candidates:
        selected = _is_selected(candidate)
        score = _candidate_score(candidate)
        if selected:
            if score is None:
                selected_without_score += 1
            else:
                selected_scores.append(score)
            symbol = str(candidate.get("symbol") or "")
            timestamp = _candidate_timestamp(candidate)
            if symbol and timestamp and len(timestamp) >= 10:
                symbol_day_counts[f"{symbol}_{timestamp[:10]}"] += 1
            else:
                failed_blockers.add("SELECTED_CANDIDATE_IDENTITY_MISSING")
        else:
            if score is None:
                rejected_without_score += 1
            else:
                rejected_scores.append(score)

    selected_count = sum(1 for candidate in candidates if _is_selected(candidate))
    if selected_count == 0:
        failed_blockers.add("NO_SELECTED_CANDIDATES")
    if selected_without_score > 0:
        failed_blockers.add("SELECTED_SCORE_EVIDENCE_MISSING")

    max_possible_trades = active_symbol_days * max_trades_per_symbol_day
    if max_possible_trades > 0 and selected_count > max_possible_trades:
        failed_blockers.add("CAPACITY_ACCOUNTING_INVARIANT_FAILED")
    cap_saturation_ratio = (
        selected_count / max_possible_trades if max_possible_trades > 0 else None
    )
    capped_days = sum(
        1
        for count in symbol_day_counts.values()
        if count >= max_trades_per_symbol_day > 0
    )
    percent_symbol_days_at_cap = (
        capped_days / active_symbol_days if active_symbol_days > 0 else None
    )
    zero_trade_days = max(active_symbol_days - len(symbol_day_counts), 0)
    one_trade_days = sum(1 for count in symbol_day_counts.values() if count == 1)

    def percentile(values: list[float], quantile: int) -> float | None:
        return float(np.percentile(values, quantile)) if values else None

    selected_p50 = percentile(selected_scores, 50)
    rejected_p50 = percentile(rejected_scores, 50)
    score_gap = (
        selected_p50 - rejected_p50
        if selected_p50 is not None and rejected_p50 is not None
        else None
    )

    if cap_saturation_ratio is not None and cap_saturation_ratio > 0.70:
        failed_blockers.add("SELECTION_CAP_SATURATION_FAILED")
    if (
        percent_symbol_days_at_cap is not None
        and percent_symbol_days_at_cap > 0.40
    ):
        failed_blockers.add("SYMBOL_DAY_CAP_SATURATION_FAILED")
    if score_gap is not None and score_gap < 5:
        failed_blockers.add("WEAK_SCORE_SEPARATION_FAILED")

    blockers = sorted(failed_blockers)
    return {
        "classification": (
            "PHASE_4_8_SELECTION_QUALITY_FAILED"
            if blockers
            else "PHASE_4_8_SELECTION_QUALITY_PASSED"
        ),
        "blockers": blockers,
        "metrics": {
            "selected_score_min": min(selected_scores) if selected_scores else None,
            "selected_score_p25": percentile(selected_scores, 25),
            "selected_score_p50": selected_p50,
            "selected_score_p75": percentile(selected_scores, 75),
            "selected_score_max": max(selected_scores) if selected_scores else None,
            "rejected_score_p50": rejected_p50,
            "selected_vs_rejected_score_gap": score_gap,
            "selected_candidates_without_score": selected_without_score,
            "rejected_candidates_without_score": rejected_without_score,
            "parquet_symbol_days": active_symbol_days,
            "candidate_symbol_days": len(symbol_day_counts),
            "ledger_symbol_days": len(symbol_day_counts),
            "active_symbol_days_used_for_capacity": active_symbol_days,
            "selected_trades": selected_count,
            "max_trades_per_symbol_day": max_trades_per_symbol_day,
            "max_possible_trades": max_possible_trades,
            "selected_minus_capacity": selected_count - max_possible_trades,
            "symbol_days_missing_from_candidates": zero_trade_days,
            "symbol_days_missing_from_ledger": zero_trade_days,
            "cap_saturation_ratio": cap_saturation_ratio,
            "symbol_days_at_cap": capped_days,
            "percent_symbol_days_at_cap": percent_symbol_days_at_cap,
            "zero_trade_days": zero_trade_days,
            "one_trade_days": one_trade_days,
            "capped_trade_days": capped_days,
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strategy", type=str, required=True)
    args = parser.parse_args()

    base_dir = Path(f"runtime/strategy_validation/{args.strategy}")
    candidates_path = base_dir / "phase_4_candidates.jsonl"
    metadata_path = base_dir / "simulation_metadata.json"
    summary_path = base_dir / "phase_4_trade_ledger_summary.json"

    candidates: list[dict[str, Any]] = []
    if candidates_path.exists():
        for line in candidates_path.read_text().splitlines():
            if line.strip():
                candidates.append(json.loads(line))
    metadata = (
        json.loads(metadata_path.read_text()) if metadata_path.exists() else {}
    )
    summary = json.loads(summary_path.read_text()) if summary_path.exists() else {}
    metadata = _capacity_metadata(metadata, summary)

    report = audit_selection_quality(candidates, metadata)
    report["strategy_id"] = args.strategy
    base_dir.mkdir(parents=True, exist_ok=True)
    (base_dir / "phase_4_8_selection_quality_audit.json").write_text(
        json.dumps(report, indent=2)
    )
    print(
        "Phase 4.8 Selection Quality Audit complete. "
        f"Result: {report['classification']}"
    )


if __name__ == "__main__":
    main()
