#!/usr/bin/env python3
from __future__ import annotations
import hashlib,sys
REVIEW_ROLES=['contract_compliance','negative_control','evidence_provenance','authority_promotion','causal_time','denominator_search_integrity','runtime_boundary','qa_verification','architecture_no_drift','adversarial_red_team','reproducibility']
AUDIT_ROLES=['evidence_chain','review_independence','acceptance_criteria','regression','program_state','scope_no_drift','scientific_integrity','reproducibility','authority','adversarial_acceptance','artifact_completeness']
def finding(fid,sev):return {'finding_id':fid,'severity':sev,'requirement':'calibration requirement','evidence':'controlled calibration evidence','falsifier':'controlled opposite behavior','recommended_repair_scope':'calibration only'}
def jobid(i,kind='R'):return hashlib.md5(f'{kind}{i}'.encode()).hexdigest()
def review(i,head,verdict='PASS',fs=None,role=None):
 fs=fs or [];rid=f'R{i:02d}';jid=jobid(i,'R');packet=f'packets/{rid}.md';output=f'reviews/reviewer-{i:02d}.json'
 return {'artifact_id':f'CAL-{rid}','sprint':'S003','round':'R001','candidate_head':head,'role':role or REVIEW_ROLES[i-1],'execution_role_id':rid,'execution_job_id':jid,'transport':'mac_git_mailbox','packet_path':packet,'output_path':output,'runtime_authority':'NONE','broker_actions':'NONE','independent_from_implementation':True,'independent_from_review_aggregation':True,'verdict':verdict,'findings':fs,'critical':sum(x['severity']=='CRITICAL' for x in fs),'major':sum(x['severity']=='MAJOR' for x in fs),'minor':sum(x['severity']=='MINOR' for x in fs),'unknown':sum(x['severity']=='UNKNOWN' for x in fs),'evidence_refs':['CALIBRATION-CONTROL']}
def audit(i,head,verdict='PASS',fs=None,role=None):
 fs=fs or [];rid=f'A{i:02d}';jid=jobid(i,'A');packet=f'packets/{rid}.md';output=f'audits/auditor-{i:02d}.json'
 return {'artifact_id':f'CAL-{rid}','sprint':'S003','round':'A001','candidate_head':head,'role':role or AUDIT_ROLES[i-1],'execution_role_id':rid,'execution_job_id':jid,'transport':'mac_git_mailbox','packet_path':packet,'output_path':output,'runtime_authority':'NONE','broker_actions':'NONE','independent_from_implementation':True,'independent_from_review_aggregation':True,'verdict':verdict,'findings':fs,'critical':sum(x['severity']=='CRITICAL' for x in fs),'major':sum(x['severity']=='MAJOR' for x in fs),'minor':sum(x['severity']=='MINOR' for x in fs),'unknown':sum(x['severity']=='UNKNOWN' for x in fs),'evidence_refs':['CALIBRATION-CONTROL'],'audited_review_round':'R001','audited_native_validation':'CALIBRATION-NATIVE','audited_acceptance_criteria':['S003-AC-001'],'audit_scope':['calibration machinery']}
def receipt(a,head,job_type):return {'schema_version':1,'worker_id':'calibration-worker','runtime_authority':'NONE','broker_actions_allowed':False,'request':{'candidate_sha':head,'job_type':job_type,'role_id':a['execution_role_id'],'packet_path':a['packet_path'],'output_path':a['output_path']},'job':{'candidate_sha':head,'job_type':job_type,'role_id':a['execution_role_id'],'job_id':a['execution_job_id'],'packet_path':a['packet_path'],'output_path':a['output_path'],'state':'SUCCEEDED','exit_code':0,'command_hash':'a'*64,'created_at':1.0,'started_at':2.0,'finished_at':3.0}}
def manifest(items,head,job_type,round_id):return {'schema_version':'mros-agent-population-v1','job_type':job_type,'candidate_head':head,'sprint':'S003','round':round_id,'frozen_before_execution':True,'expected_count':len(items),'members':[{'execution_role_id':a['execution_role_id'],'semantic_role':a['role'],'packet_path':a['packet_path'],'output_path':a['output_path'],'receipt_path':f"receipts/{a['execution_role_id']}.json"} for a in items]}
def bundle(items,head,job_type,round_id):return [(a['output_path'],a) for a in items],{a['execution_job_id']:receipt(a,head,job_type) for a in items},manifest(items,head,job_type,round_id)
def native(head):
 source='CALIBRATION_NATIVE_OUTPUT';jid=jobid(96,'R');sha=hashlib.sha256(source.encode()).hexdigest()
 d={'schema_version':'mros-native-evidence-v2','evidence_kind':'native_validation','repository':'ramgolladi1503-sys/tradebot','branch':'research/mros-program-v1','head':head,'validator':'scripts/mros/calibrate_review_audit_board.py','python_version':f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}','command':f'python3 scripts/mros/calibrate_review_audit_board.py --candidate-head {head}','checks':32,'passed':32,'failed':0,'exit_code':0,'timestamp':'2026-08-08T00:00:00Z','transport':'mac_git_mailbox','execution_job_id':jid,'execution_receipt_ref':'receipts/R96.json','source_output_ref':'results/R96.txt','source_output_sha256':sha,'runtime_authority':'NONE','broker_actions':'NONE'}
 r={'runtime_authority':'NONE','broker_actions_allowed':False,'request':{'candidate_sha':head},'job':{'candidate_sha':head,'job_id':jid,'state':'SUCCEEDED','exit_code':0}}
 return d,source,r
def accept_trace(head,ok=True):return {'schema_version':'mros-sprint-acceptance-trace-v1','sprint':'S003','candidate_head':head,'authority':'Research / R','runtime_authority':'NONE','m9_status':'NOT_STARTED','criteria':[{'id':'S003-AC-001','status':'PASS' if ok else 'FAIL','evidence_refs':['CAL-OUT']}]}
def state_text(active='S003',runtime='NONE',m9='NOT_STARTED'):return f'active_sprint: {active}\nmilestone_status:\n  M9: {m9}\nauthority:\n  runtime_authority: {runtime}\n'
def ledger_text():
 import json
 return json.dumps({'sprint_id':'S003','decision':'ACTIVE'})+'\n'
