from enum import Enum


class DriftType(Enum):
    NO_DRIFT = "NO_DRIFT"
    EXPECTANCY_DRIFT = "EXPECTANCY_DRIFT"
    PROFIT_FACTOR_DRIFT = "PROFIT_FACTOR_DRIFT"
    DRAWDOWN_DRIFT = "DRAWDOWN_DRIFT"
    REGIME_DRIFT = "REGIME_DRIFT"
    EXECUTION_DRIFT = "EXECUTION_DRIFT"
    DATA_QUALITY_DRIFT = "DATA_QUALITY_DRIFT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"


class LifecycleState(Enum):
    PRODUCTION_CANDIDATE = "PRODUCTION_CANDIDATE"
    WARNING = "WARNING"
    UNDER_REVIEW = "UNDER_REVIEW"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"


class ActionRecommendation(Enum):
    NO_ACTION = "NO_ACTION"
    MONITOR = "MONITOR"
    COLLECT_MORE_DATA = "COLLECT_MORE_DATA"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SUSPEND_RECOMMENDED = "SUSPEND_RECOMMENDED"
    REVOKE_RECOMMENDED = "REVOKE_RECOMMENDED"
